apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DATABASE_USER: YWRtaW4= # Usuário codificada em base64
  DATABASE_PASSWORD: NTgyYWRmRXQ= # Senha codificada em base64
  AWS_ACCESS_KEY_ID: QUtJQTQyTVFETDVPMzdGM1FHVkk=
  AWS_SECRET_ACCESS_KEY: RGFNYWswVHdCeVdqQXU3Qy8rSjVFaUFCUERCR29VWW9zMWRiTE9SVQ==