name: Deploy to AWS EKS

env:
  AWS_REGION: us-east-2
  AWS_ASSUME_ROLE: arn:aws:iam::881307377501:role/github-actions-fiap-pipelike
  #ECR_REGISTRY: 881307377501.dkr.ecr.us-east-2.amazonaws.com/cormus
  ECR_REPOSITORY: cormus

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon EKS
      run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name springboot-eks

    - name: Apply k8s in Amazon EKS
      run: |
        kubectl apply -f k8s/mysql-configmap.yaml
        kubectl apply -f k8s/mysql-secret.yaml
        kubectl apply -f k8s/node-deployment.yaml
        kubectl apply -f k8s/spring-pagamento-deployment.yaml